template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-Stranger}

# Database settings.
database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: create
#    hibernate.dialect: org.hibernate.dialect.MySQLDialect


server:
  #  softNofileLimit: 1000
  #  hardNofileLimit: 1000
  type: default
  applicationConnectors:
  - type: http
    port: 8080
#  - type: https
#    port: 8443
#    keyStorePath: example.keystore
#    keyStorePassword: example
  #this requires the alpn-boot library on the JVM's boot classpath
  #- type: h2
  #  port: 8445
  #  keyStorePath: example.keystore
  #  keyStorePassword: example
  adminConnectors:
  - type: http
    port: 8081
#  - type: https
#    port: 8444
#    keyStorePath: example.keystore
#    keyStorePassword: example

# Logging settings.
logging:
  level: INFO
  loggers:
    dw.ms.app: DEBUG
    org.hibernate.SQL:
      level: DEBUG

  appenders:
  - type: console
  - type: file
    threshold: INFO
    logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
    currentLogFilename: /tmp/application.log
    archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
    archivedFileCount: 7
    timeZone: UTC
    maxFileSize: 10MB

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
  freemarker:
    strict_syntax: yes
    whitespace_stripping: yes

#metrics:
#  reporters:
#  - type: graphite
#    host: localhost
#    port: 2003
#    prefix: example
#    frequency: 1m
